/**
 * yang7758258/ohhh_QL-Script
 * @type {import('@lzwme/whistle.x-scripts').RuleItem[]}
 */
module.exports = [
  {
    on: 'req-body',
    ruleId: 'chmlck',
    desc: '长虹美菱小程序签到',
    url: 'https://hongke.changhong.com/gw/burying/burying/report*',
    method: 'post',
    getCacheUid: ({ reqBody: R }) => R?.props?.wx_user?.phone_number,
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers.token}##${d.uid}`).join('\n') } }),
  },
  {
    on: 'res-body',
    ruleId: 'qchyjlb',
    desc: '雀巢会员俱乐部小程序签到',
    url: 'https://crm.nestlechinese.com/openapi/member/api/User/GetUserInfo',
    method: 'get',
    getCacheUid: ({ resBody: R }) => ({ uid: R?.data?.mobile }),
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers.authorization}&${d.uid}`).join('\n') } }),
    updateEnvValue: /&([\d\*]+)/,
  },
  {
    on: 'res-body',
    ruleId: 'fsdlb',
    desc: '逢三得利吧小程序签到',
    url: 'https://xiaodian.miyatech.com/api/user/member/info',
    method: 'post',
    getCacheUid: ({ resBody: R }) => ({ uid: R?.data?.memberId }),
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers.authorization}&${d.uid}`).join('\n') } }),
    updateEnvValue: /&([\d\*]+)/,
  },
  {
    on: 'res-body',
    ruleId: 'ywxspc',
    desc: '义乌小商品城会员小程序签到',
    url: 'https://apiserver.chinagoods.com/ums/authentication/v1/userauthinfo',
    method: 'get',
    getCacheUid: ({ resBody: R }) => ({ uid: R?.data?.userinfo?.userId }),
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers.authorization}&${d.uid}`).join('\n') } }),
    updateEnvValue: /&([\d\*]+)/,
  },
  {
    on: 'res-body',
    ruleId: 'zippo',
    desc: 'zippo会员中心小程序签到',
    url: 'https://wx-center.zippo.com.cn/api/users/profile',
    method: 'post',
    getCacheUid: ({ resBody: R }) => ({ uid: R?.phone }),
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers.authorization}&${d.uid}`).join('\n') } }),
    updateEnvValue: /&([\d\*]+)/,
  },
  {
    on: 'res-body',
    ruleId: 'gmjkck',
    desc: '敢迈健康+小程序签到',
    url: 'https://api.digital4danone.com.cn/healthyaging/danone/wx/ha/haUser/info',
    method: 'get',
    getCacheUid: ({ resBody: R }) => ({ uid: R?.result?.userId }),
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers['x-access-token']}`).join('\n') } }),
    // updateEnvValue: /&([\d\*]+)/,
  },
  {
    on: 'res-body',
    ruleId: 'huangzuan_WX',
    desc: '媓钻小程序签到',
    url: 'https://api.hzyxhfp.com/api/userRight/getUserRightDetail',
    method: 'post',
    getCacheUid: ({ resBody: R }) => ({ uid: R?.data?.phone }),
    handler: ({ cacheData: D }) => ({ envConfig: { value: D.map(d => `${d.headers.authorization.replace('Bearer ', '')}`).join('\n') } }),
    // updateEnvValue: /&([\d\*]+)/,
  },
];
